# Generated by Django 5.1.3 on 2025-01-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about_us/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Настройки приложения',
                'verbose_name_plural': 'Настройки приложения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='how_it_works/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Как это работает',
                'verbose_name_plural': 'Как это работает',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='our_services/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Наши услуги',
                'verbose_name_plural': 'Наши услуги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_weight', models.CharField(max_length=255, verbose_name='Описание')),
                ('text_weight', models.CharField(max_length=255, verbose_name='Текст')),
                ('description_payment', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Данные оплаты',
                'verbose_name_plural': 'Данные оплаты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PriceAndPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('type_of_service', models.CharField(max_length=255, verbose_name='Тип услуги')),
                ('price_usa', models.CharField(max_length=255, verbose_name='Цена в США')),
                ('price_turkey', models.CharField(max_length=255, verbose_name='Цена в Турции')),
                ('price_china_air', models.CharField(max_length=255, verbose_name='Цена в Китай(Авиа)')),
                ('price_china_car', models.CharField(max_length=255, verbose_name='Цена в Китай(Авто)')),
                ('commission', models.CharField(max_length=255, verbose_name='Комиссия')),
            ],
            options={
                'verbose_name': 'Цена и оплата',
                'verbose_name_plural': 'Цена и оплата',
                'ordering': ['id'],
            },
        ),
    ]
