# Generated by Django 5.1.3 on 2025-01-16 04:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст')),
                ('image1', models.ImageField(upload_to='about_us_page/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(upload_to='about_us_page/', verbose_name='Изображение 2')),
            ],
            options={
                'verbose_name': 'Страница О нас',
                'verbose_name_plural': 'Страница О нас',
            },
        ),
    ]
