# Generated by Django 5.1.3 on 2025-01-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0002_aboutuspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Телефон')),
                ('working_hours', models.CharField(max_length=255, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'ПВЗ',
                'verbose_name_plural': 'ПВЗ',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='priceandpayment',
            name='weight',
            field=models.CharField(choices=[('0+', '0+'), ('100+', '100+'), ('200+', '200+')], max_length=255, verbose_name='Вес'),
        ),
    ]
