# Generated by Django 5.1.3 on 2025-02-25 11:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='text_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='text_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='text_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ky',
            field=models.TextField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ky',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ky',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='howitworks',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='description_payment_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='description_payment_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='description_payment_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='description_weight_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='description_weight_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='description_weight_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='subtitle_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='text_weight_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='text_weight_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='text_weight_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='commission_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Комиссия'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='commission_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Комиссия'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='commission_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Комиссия'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_china_air_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в Китай(Авиа)'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_china_air_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в Китай(Авиа)'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_china_air_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в Китай(Авиа)'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_china_car_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в Китай(Авто)'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_china_car_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в Китай(Авто)'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_china_car_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в Китай(Авто)'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_turkey_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в Турции'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_turkey_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в Турции'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_turkey_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в Турции'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_usa_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в США'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_usa_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в США'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='price_usa_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена в США'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='type_of_service_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='type_of_service_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='type_of_service_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='weight_en',
            field=models.CharField(choices=[('0+', '0+'), ('100+', '100+'), ('200+', '200+')], max_length=255, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='weight_ky',
            field=models.CharField(choices=[('0+', '0+'), ('100+', '100+'), ('200+', '200+')], max_length=255, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='priceandpayment',
            name='weight_ru',
            field=models.CharField(choices=[('0+', '0+'), ('100+', '100+'), ('200+', '200+')], max_length=255, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='location_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='location_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='phone_number_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='phone_number_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='phone_number_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='working_hours_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='working_hours_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='pvz',
            name='working_hours_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Время работы'),
        ),
    ]
