# Generated by Django 5.1.3 on 2025-02-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0005_aboutus_description_en_aboutus_description_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceandpayment',
            name='weight_en',
        ),
        migrations.RemoveField(
            model_name='priceandpayment',
            name='weight_ky',
        ),
        migrations.RemoveField(
            model_name='priceandpayment',
            name='weight_ru',
        ),
        migrations.RemoveField(
            model_name='pvz',
            name='phone_number_en',
        ),
        migrations.RemoveField(
            model_name='pvz',
            name='phone_number_ky',
        ),
        migrations.RemoveField(
            model_name='pvz',
            name='phone_number_ru',
        ),
    ]
