# Generated by Django 5.1.3 on 2025-01-24 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Содержимое')),
                ('type_of_packaging', models.CharField(blank=True, max_length=255, verbose_name='Тип упаковки')),
                ('track_number', models.CharField(blank=True, max_length=255, verbose_name='Трек номер')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('warehouse', models.CharField(blank=True, max_length=255, verbose_name='Склад')),
                ('store', models.CharField(blank=True, max_length=255, verbose_name='Магазин')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='Статус')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес')),
                ('summa', models.IntegerField(blank=True, null=True, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Посылка',
                'verbose_name_plural': 'Посылки',
            },
        ),
    ]
