# Generated by Django 5.1.3 on 2025-01-24 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название магазина')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.RenameField(
            model_name='package',
            old_name='track_number',
            new_name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='package',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='summa',
        ),
        migrations.RemoveField(
            model_name='package',
            name='weight',
        ),
        migrations.AddField(
            model_name='package',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='package',
            name='client_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AddField(
            model_name='package',
            name='count_scans',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество сканов'),
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='package',
            name='final_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итоговый вес'),
        ),
        migrations.AddField(
            model_name='package',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия и Имя'),
        ),
        migrations.AddField(
            model_name='package',
            name='invoice_image',
            field=models.ImageField(blank=True, upload_to='invoice_images/', verbose_name='Фото инвойса'),
        ),
        migrations.AddField(
            model_name='package',
            name='label_image',
            field=models.ImageField(blank=True, upload_to='label_images/', verbose_name='Фото лэйбла'),
        ),
        migrations.AddField(
            model_name='package',
            name='manual_editing',
            field=models.BooleanField(default=False, verbose_name='Ручное редактирование'),
        ),
        migrations.AddField(
            model_name='package',
            name='options_of_packaging',
            field=models.CharField(blank=True, choices=[('Отправить в почтовой упаковке', 'Отправить в почтовой упаковке'), ('Сохранить обувную коробку', 'Сохранить обувную коробку')], max_length=255, verbose_name='Опции упаковки'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_image',
            field=models.ImageField(blank=True, upload_to='package_images/', verbose_name='Фото посылки'),
        ),
        migrations.AddField(
            model_name='package',
            name='weight_of_package',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес по складу'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(blank=True, choices=[('Проверяется', 'Проверяется'), ('Ждем на склад', 'Ждем на склад'), ('На складе', 'На складе'), ('Отправлена', 'Отправлена'), ('На обработке', 'На обработке'), ('Прибыла', 'Прибыла'), ('Доставлена заказчику', 'Доставлена заказчику'), ('Неправильный трекинг номер', 'Неправильный трекинг номер'), ('Возвращена отправителю', 'Возвращена отправителю'), ('Задержана на складе', 'Задержана на складе'), ('Отменена', 'Отменена')], max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='package',
            name='type_of_packaging',
            field=models.CharField(blank=True, choices=[('Пакет', 'Пакет'), ('Коробка', 'Коробка')], max_length=255, verbose_name='Тип упаковки'),
        ),
        migrations.AlterField(
            model_name='package',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('США', 'США'), ('Турция', 'Турция'), ('Китай', 'Китай'), ('Япония', 'Япония')], max_length=255, verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='package_images/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_images', to='packages.package', verbose_name='Посылка')),
            ],
            options={
                'verbose_name': 'Фото посылки',
                'verbose_name_plural': 'Фото посылок',
            },
        ),
        migrations.CreateModel(
            name='PackageWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_place', models.IntegerField(blank=True, null=True, verbose_name='Количество мест')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес')),
                ('is_volume_weight', models.BooleanField(default=False, verbose_name='Обьемный вес')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Длина')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('volume_weight', models.IntegerField(blank=True, null=True, verbose_name='Обьемный вес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_weights', to='packages.package', verbose_name='Посылка')),
            ],
            options={
                'verbose_name': 'Вес посылки',
                'verbose_name_plural': 'Вес посылок',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='packages.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('summa', models.IntegerField(blank=True, null=True, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_details', to='packages.package', verbose_name='Посылка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_details', to='packages.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Детали посылки',
                'verbose_name_plural': 'Детали посылок',
            },
        ),
        migrations.AlterField(
            model_name='package',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.store', verbose_name='Магазин'),
        ),
    ]
