# Generated by Django 5.1.3 on 2025-01-27 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_category_store_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='final_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Итоговый вес'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight_of_package',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес по складу'),
        ),
        migrations.AlterField(
            model_name='packageweight',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=255, verbose_name='Трек номер')),
                ('tracking_number_2', models.CharField(blank=True, max_length=255, verbose_name='Трек номер 2')),
                ('type', models.CharField(blank=True, choices=[('Входящие', 'Входящие'), ('Исходящие', 'Исходящие')], max_length=255, verbose_name='Тип')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Локация')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата сканирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Скан',
                'verbose_name_plural': 'Сканы',
            },
        ),
    ]
