# Generated by Django 5.1.3 on 2025-01-29 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_final_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='package',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_images/', verbose_name='Фото инвойса'),
        ),
        migrations.AlterField(
            model_name='package',
            name='label_image',
            field=models.ImageField(blank=True, null=True, upload_to='label_images/', verbose_name='Фото лэйбла'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/', verbose_name='Фото посылки'),
        ),
        migrations.AlterField(
            model_name='package',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
