# Generated by Django 5.1.3 on 2025-01-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_location_alter_package_store_alter_scan_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='packages.location', verbose_name='Локация'),
        ),
    ]
