# Generated by Django 5.1.3 on 2025-01-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_scan_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetail',
            name='summa',
        ),
        migrations.AddField(
            model_name='package',
            name='reys',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рейс'),
        ),
        migrations.AddField(
            model_name='package',
            name='summa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
