# Generated by Django 5.1.3 on 2025-02-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_remove_packagedetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_at'], 'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': 'Посылка', 'verbose_name_plural': 'Посылки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Скан', 'verbose_name_plural': 'Сканы'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at'], 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AddField(
            model_name='package',
            name='date_on_warehouse',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата на складе'),
        ),
    ]
