# Generated by Django 5.1.3 on 2025-02-05 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_alter_category_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='Номер')),
                ('count_place', models.IntegerField(blank=True, null=True, verbose_name='Количество мест')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
                ('reys', models.CharField(blank=True, max_length=255, verbose_name='Рейс')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('warehouse', models.CharField(blank=True, choices=[('США', 'США'), ('Турция', 'Турция'), ('Китай', 'Китай'), ('Япония', 'Япония')], max_length=255, verbose_name='Склад')),
                ('sender', models.CharField(blank=True, max_length=255, verbose_name='Отправитель')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='Получатель')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('image', models.ImageField(blank=True, null=True, upload_to='awb_images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'AWB',
                'verbose_name_plural': 'AWB',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('usa_address_1', models.CharField(blank=True, max_length=255, verbose_name='Адрес 1')),
                ('usa_address_2', models.CharField(blank=True, max_length=255, verbose_name='Адрес 2')),
                ('usa_city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('usa_state', models.CharField(blank=True, max_length=255, verbose_name='Штат')),
                ('usa_zip_code', models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс')),
                ('usa_phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('turkey_city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('turkey_rayon', models.CharField(blank=True, max_length=255, verbose_name='Район')),
                ('turkey_quarter', models.CharField(blank=True, max_length=255, verbose_name='Квартал')),
                ('turkey_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('turkey_post_code', models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс')),
                ('turkey_phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('china_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('china_phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('china_region', models.CharField(blank=True, max_length=255, verbose_name='Регион')),
                ('china_detail_address', models.CharField(blank=True, max_length=255, verbose_name='Детальный адрес')),
                ('china_post_code', models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс')),
                ('japan_city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('japan_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('japan_post_code', models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс')),
                ('japan_phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Данные складов',
                'verbose_name_plural': 'Данные складов',
            },
        ),
        migrations.RemoveField(
            model_name='package',
            name='admin_comment',
        ),
        migrations.RemoveField(
            model_name='package',
            name='manual_editing',
        ),
        migrations.RemoveField(
            model_name='package',
            name='summa',
        ),
        migrations.AddField(
            model_name='package',
            name='cladovshik_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий кладовщика'),
        ),
        migrations.AddField(
            model_name='package',
            name='manager_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AddField(
            model_name='package',
            name='system_comment',
            field=models.TextField(blank=True, verbose_name='Системный комментарий'),
        ),
        migrations.AddField(
            model_name='package',
            name='whole_summa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='summa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='summa_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма в евро'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='package',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='packagedetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='packageweight',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='packageweight',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='packageweight',
            name='volume_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Обьемный вес'),
        ),
        migrations.AlterField(
            model_name='packageweight',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.CreateModel(
            name='AWBFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(blank=True, null=True, upload_to='awb_files/', verbose_name='Файл')),
                ('awb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awb_files', to='packages.awb', verbose_name='AWB')),
            ],
            options={
                'verbose_name': 'Файл AWB',
                'verbose_name_plural': 'Файлы AWB',
            },
        ),
    ]
