# Generated by Django 5.1.3 on 2025-02-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_awb_warehousedata_remove_package_admin_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(blank=True, choices=[('Проверяется', 'Проверяется'), ('Ждем на склад', 'Ждем на склад'), ('На складе', 'На складе'), ('Отправлена', 'Отправлена'), ('На обработке', 'На обработке'), ('Прибыла', 'Прибыла'), ('Доставлена заказчику', 'Доставлена заказчику'), ('Неправильный трекинг номер', 'Неправильный трекинг номер'), ('Возвращена отправителю', 'Возвращена отправителю'), ('Задержана на складе', 'Задержана на складе'), ('Отменена', 'Отменена')], default='Проверяется', max_length=255, verbose_name='Статус'),
        ),
    ]
