# Generated by Django 5.1.3 on 2025-02-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='whole_summa_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма в евро'),
        ),
    ]
