# Generated by Django 5.1.3 on 2025-03-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_package_whole_summa_eur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('year', models.CharField(blank=True, max_length=255, verbose_name='Год')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='awb',
            name='reys',
        ),
        migrations.RemoveField(
            model_name='package',
            name='reys',
        ),
    ]
