# Generated by Django 5.1.3 on 2025-03-04 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_reys_remove_awb_reys_remove_package_reys'),
    ]

    operations = [
        migrations.AddField(
            model_name='awb',
            name='reys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awbs', to='packages.reys', verbose_name='Рейс'),
        ),
        migrations.AddField(
            model_name='package',
            name='reys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.reys', verbose_name='Рейс'),
        ),
    ]
