# Generated by Django 5.1.3 on 2025-03-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_awb_reys_package_reys'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brutto',
            field=models.FloatField(blank=True, null=True, verbose_name='Брутто'),
        ),
    ]
