# Generated by Django 5.1.3 on 2025-03-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_product_brutto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousedata',
            name='japan_address',
        ),
        migrations.RemoveField(
            model_name='warehousedata',
            name='japan_city',
        ),
        migrations.RemoveField(
            model_name='warehousedata',
            name='japan_phone',
        ),
        migrations.RemoveField(
            model_name='warehousedata',
            name='japan_post_code',
        ),
        migrations.RemoveField(
            model_name='warehousedata',
            name='turkey_address',
        ),
        migrations.RemoveField(
            model_name='warehousedata',
            name='turkey_city',
        ),
        migrations.RemoveField(
            model_name='warehousedata',
            name='turkey_phone',
        ),
        migrations.RemoveField(
            model_name='warehousedata',
            name='turkey_post_code',
        ),
        migrations.RemoveField(
            model_name='warehousedata',
            name='turkey_quarter',
        ),
        migrations.RemoveField(
            model_name='warehousedata',
            name='turkey_rayon',
        ),
        migrations.AlterField(
            model_name='awb',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('США', 'США'), ('Китай', 'Китай')], max_length=255, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='package',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('США', 'США'), ('Китай', 'Китай')], max_length=255, verbose_name='Склад'),
        ),
    ]
