# Generated by Django 5.1.3 on 2026-03-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_remove_warehousedata_japan_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='cladovshik_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий кладовщика'),
        ),
        migrations.AlterField(
            model_name='package',
            name='client_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='package',
            name='manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AlterField(
            model_name='package',
            name='system_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Системный комментарий'),
        ),
    ]
