# Generated by Django 5.1.3 on 2025-01-20 05:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='ID клиента')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Страна')),
                ('phone_number', models.CharField(blank=True, max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Почта')),
                ('tarif_usa', models.CharField(blank=True, max_length=255, verbose_name='Тариф США')),
                ('tarif_usa_value', models.IntegerField(blank=True, null=True, verbose_name='Тариф США значение')),
                ('tarif_turkey', models.CharField(blank=True, max_length=255, verbose_name='Тариф Турция')),
                ('tarif_turkey_value', models.IntegerField(blank=True, null=True, verbose_name='Тариф Турция значение')),
                ('tarif_china', models.CharField(blank=True, max_length=255, verbose_name='Тариф Китай')),
                ('tarif_china_value', models.IntegerField(blank=True, null=True, verbose_name='Тариф Китай значение')),
                ('tarif_japan', models.CharField(blank=True, max_length=255, verbose_name='Тариф Япония')),
                ('tarif_japan_value', models.IntegerField(blank=True, null=True, verbose_name='Тариф Япония значение')),
                ('inn', models.CharField(blank=True, max_length=255, verbose_name='ИНН')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='Статус')),
                ('passport_number', models.CharField(blank=True, max_length=255, verbose_name='Номер удостоверения личности')),
                ('passport_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи удостоверения личности')),
                ('passport_place', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан')),
                ('passport_image_1', models.ImageField(blank=True, upload_to='passport_images/', verbose_name='Фото удостоверения личности')),
                ('passport_image_2', models.ImageField(blank=True, upload_to='passport_images/', verbose_name='Фото удостоверения личности')),
                ('contract', models.CharField(blank=True, max_length=255, verbose_name='Договор')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
