# Generated by Django 5.1.3 on 2025-01-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['is_active'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
    ]
