# Generated by Django 5.1.3 on 2025-02-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='tarif_china_weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тариф Китай: Вес'),
        ),
        migrations.AddField(
            model_name='user',
            name='tarif_japan_weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тариф Япония: Вес'),
        ),
        migrations.AddField(
            model_name='user',
            name='tarif_turkey_weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тариф Турция: Вес'),
        ),
        migrations.AddField(
            model_name='user',
            name='tarif_usa_weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тариф США: Вес'),
        ),
    ]
