# Generated by Django 5.1.3 on 2025-02-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_resipient_alter_user_options_user_tarif_china_weight_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resipient',
        ),
    ]
