# Generated by Django 5.1.3 on 2025-02-05 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_resipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='user',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_image_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_image_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_china',
            field=models.CharField(blank=True, choices=[('Новичок', 'Новичок'), ('VIP', 'VIP')], default='Новичок', max_length=255, verbose_name='Тариф Китай'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_china_value',
            field=models.FloatField(blank=True, default=3.4, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_china_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Тариф Китай: Вес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_japan',
            field=models.CharField(blank=True, choices=[('Новичок', 'Новичок'), ('VIP', 'VIP')], default='Новичок', max_length=255, verbose_name='Тариф Япония'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_japan_value',
            field=models.FloatField(blank=True, default=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_japan_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Тариф Япония: Вес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_turkey',
            field=models.CharField(blank=True, choices=[('Новичок', 'Новичок'), ('VIP', 'VIP')], default='Новичок', max_length=255, verbose_name='Тариф Турция'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_turkey_value',
            field=models.FloatField(blank=True, default=5.44, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_turkey_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Тариф Турция: Вес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_usa',
            field=models.CharField(blank=True, choices=[('Новичок', 'Новичок'), ('VIP', 'VIP')], default='Новичок', max_length=255, verbose_name='Тариф США'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_usa_value',
            field=models.FloatField(blank=True, default=11, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_usa_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Тариф США: Вес'),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('status_recipient', models.CharField(blank=True, max_length=255, verbose_name='Статус получателя')),
                ('passport_number', models.CharField(blank=True, max_length=255, verbose_name='Номер удостоверения личности')),
                ('passport_place', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан')),
                ('passport_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи удостоверения личности')),
                ('passport_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания удостоверения личности')),
                ('inn', models.CharField(blank=True, max_length=255, verbose_name='ИНН')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('passport_image_1', models.ImageField(blank=True, upload_to='passport_images/', verbose_name='Фото удостоверения личности')),
                ('passport_image_2', models.ImageField(blank=True, upload_to='passport_images/', verbose_name='Фото удостоверения личности')),
                ('portret_image', models.ImageField(blank=True, upload_to='portret_images/', verbose_name='Портрет')),
                ('contract', models.CharField(blank=True, max_length=255, verbose_name='Договор')),
                ('main_recipient', models.BooleanField(default=False, verbose_name='Основной получатель')),
                ('comment_for_manager', models.TextField(blank=True, verbose_name='Комментарий для менеджера')),
                ('comment_for_client', models.TextField(blank=True, verbose_name='Комментарий для клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.country', verbose_name='Страна')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'ordering': ['-created_at'],
            },
        ),
    ]
