# Generated by Django 5.1.3 on 2025-02-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_address_remove_user_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='status_recipient',
            field=models.CharField(choices=[('Проверяется', 'Проверяется'), ('Отклонен', 'Отклонен'), ('Подтвержден', 'Подтвержден')], default='Проверяется', max_length=255, verbose_name='Статус получателя'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
