# Generated by Django 5.1.3 on 2025-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_recipient_status_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tarif_china_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Тариф Китай: Вес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_japan_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Тариф Япония: Вес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_turkey_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Тариф Турция: Вес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_usa_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Тариф США: Вес'),
        ),
    ]
