# Generated by Django 5.1.3 on 2025-03-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_confirmationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tarif_japan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tarif_japan_value',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tarif_japan_weight',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tarif_turkey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tarif_turkey_value',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tarif_turkey_weight',
        ),
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='ID клиента'),
        ),
    ]
