# Generated by Django 5.1.3 on 2025-03-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_tarif_japan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tarif_china_value',
            field=models.FloatField(blank=True, default=2.8, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif_usa_value',
            field=models.FloatField(blank=True, default=9.5, null=True, verbose_name=''),
        ),
    ]
