# Generated by Django 5.1.3 on 2025-04-04 07:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Сообщение'),
        ),
    ]
